import "./setup.js";
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";
import {
  assembleDefaults,
  recipeFilesDir,
  resolveSectionFiles,
} from "../../www/js/sensorbox-recipes.js";

// The browser loads Mustache as a global from the vendored UMD bundle;
// evaluated at top level it takes the browser branch and attaches itself.
vm.runInThisContext(
  fs.readFileSync(new URL("../../www/js/vendor/mustache.min.js", import.meta.url), "utf8")
);

function reader(files) {
  const reads = [];
  const read = async (rel) => {
    reads.push(rel);
    if (!(rel in files)) throw new Error(`no such file ${rel}`);
    return files[rel];
  };
  read.reads = reads;
  return read;
}

async function resolved(doc, files, dir = "dev") {
  return resolveSectionFiles(doc, dir, reader(files));
}

describe("recipeFilesDir", () => {
  it("strips the YAML extension", () => {
    assert.equal(recipeFilesDir("friendlyarm_nanopi-zero2.yaml"), "friendlyarm_nanopi-zero2");
    assert.equal(recipeFilesDir("_common.yaml"), "_common");
  });
});

describe("resolveSectionFiles", () => {
  it("reads each source relative to the recipe's directory", async () => {
    const read = reader({ "dev/a.sh": "echo a\n", "dev/sub/b.conf": "b\n" });
    const doc = await resolveSectionFiles(
      {
        sections: [
          {
            files: {
              "/usr/bin/a": "a.sh",
              "/etc/b.conf": { src: "sub/b.conf", mode: "0600", template: true },
            },
          },
        ],
      },
      "dev",
      read
    );
    assert.deepEqual(read.reads.sort(), ["dev/a.sh", "dev/sub/b.conf"]);
    assert.deepEqual(doc.sections[0].files, [
      { path: "/usr/bin/a", src: "a.sh", mode: undefined, template: false, content: "echo a\n" },
      { path: "/etc/b.conf", src: "sub/b.conf", mode: "0600", template: true, content: "b\n" },
    ]);
  });

  it("leaves recipes without sections alone", async () => {
    const doc = { defaults: "uci commit\n" };
    assert.equal(await resolved(doc, {}), doc);
    assert.deepEqual(doc, { defaults: "uci commit\n" });
  });

  it("rejects sources outside the recipe directory", async () => {
    for (const src of ["../keys/x.pub", "/etc/passwd", "a/../../b"]) {
      await assert.rejects(
        resolved({ sections: [{ files: { "/etc/x": src } }] }, {}),
        /src must be a path inside dev\//
      );
    }
  });

  it("rejects destination paths that would need shell quoting", async () => {
    for (const path of ["etc/x", "/etc/a b", "/etc/$(id)", "/etc/'x"]) {
      await assert.rejects(
        resolved({ sections: [{ files: { [path]: "x" } }] }, { "dev/x": "" }),
        /bad file path/
      );
    }
  });

  it("requires mode to be a quoted octal string", async () => {
    // Bare 0755 parses as 755 in js-yaml and 493 in PyYAML.
    for (const mode of [755, "755x", "+x"]) {
      await assert.rejects(
        resolved({ sections: [{ files: { "/etc/x": { src: "x", mode } } }] }, { "dev/x": "" }),
        /mode must be a quoted octal string/
      );
    }
  });
});

describe("assembleDefaults with sections", () => {
  const values = { flag: true, off: false, empty: "", token: "a&b'c" };

  it("keeps plain defaults-only recipes unchanged", () => {
    const script = assembleDefaults(
      { defaults: "common {{{token}}}" },
      { id: "dev", defaults: "device" },
      values,
      ""
    );
    assert.equal(
      script,
      [
        "#!/bin/sh",
        "# Generated by sensorbox — runs once on first boot via /etc/uci-defaults/.",
        "",
        "# --- sensorbox common pre-amble ---",
        "common a&b'c",
        "# --- dev recipe ---",
        "device",
        "exit 0",
      ].join("\n")
    );
  });

  it("writes a section's files before running its defaults", async () => {
    const recipe = await resolved(
      {
        id: "dev",
        defaults: "top",
        sections: [
          {
            when: "flag",
            files: { "/etc/init.d/svc": { src: "svc.init", mode: "0755" } },
            defaults: "/etc/init.d/svc enable",
          },
        ],
      },
      { "dev/svc.init": "#!/bin/sh /etc/rc.common\nSTART=99\n" }
    );
    const script = assembleDefaults(null, recipe, values, "");
    assert.ok(
      script.includes(
        [
          "top",
          "mkdir -p /etc/init.d",
          "cat > /etc/init.d/svc <<'SENSORBOX_FILE_EOF'",
          "#!/bin/sh /etc/rc.common",
          "START=99",
          "SENSORBOX_FILE_EOF",
          "chmod 0755 /etc/init.d/svc",
          "/etc/init.d/svc enable",
        ].join("\n")
      ),
      script
    );
  });

  it("skips sections whose when flag is falsy, like {{#flag}}", async () => {
    const recipe = await resolved(
      {
        id: "dev",
        sections: [
          { when: "off", defaults: "OFF" },
          { when: "empty", defaults: "EMPTY" },
          { when: "missing", defaults: "MISSING" },
          { when: "flag", defaults: "ON" },
          { defaults: "ALWAYS" },
        ],
      },
      {}
    );
    const script = assembleDefaults(null, recipe, values, "");
    assert.ok(script.includes("ON\nALWAYS"), script);
    assert.ok(!/OFF|EMPTY|MISSING/.test(script), script);
  });

  it("copies files verbatim unless template: true", async () => {
    const recipe = await resolved(
      {
        id: "dev",
        sections: [
          {
            files: {
              "/www/index.html": "index.html",
              "/etc/config/orb": { src: "orb.config", template: true },
            },
          },
        ],
      },
      {
        "dev/index.html": "<script>const o = {{a: 1}};</script>",
        "dev/orb.config": "token={{{token}}}\n",
      }
    );
    const script = assembleDefaults(null, recipe, values, "");
    assert.ok(script.includes("<script>const o = {{a: 1}};</script>\nSENSORBOX_FILE_EOF"), script);
    assert.ok(script.includes("token=a&b'c\nSENSORBOX_FILE_EOF"), script);
  });

  it("refuses a file that would terminate its own heredoc", async () => {
    const recipe = await resolved(
      { id: "dev", sections: [{ files: { "/etc/x": "x" } }] },
      { "dev/x": "a\nSENSORBOX_FILE_EOF\nrm -rf /\n" }
    );
    assert.throws(() => assembleDefaults(null, recipe, values, ""), /SENSORBOX_FILE_EOF/);
  });
});
